### 이 코드는 테블로 시각화를 위한 데이터 전처리 과정입니다.



crawled_data : 채용사이트를 크롤링해서 얻은 데이터

In [1]:
import pandas as pd 
df = pd.read_csv("./crawled_data.csv", encoding="cp949")
df.head(3)

,직무명,회사명,위치,경력,주요업무,자격요건,우대사항
0,데이터 분석가 (3년차 이상),파이프트리스마트팜(PAIPTREESmartFarmInc.),서울 강남구,경력 3년 이상,주요업무\n? 농장의 환경 및 생체 데이터 전처리 및 feature를 추출합니다.\...,자격요건\n? 통계분석 및 모델링 개발의 리딩 경험이 풍부하신 분.\n? 3년 이상...,우대사항\n? ML/DL 관련 분야 석/박사 학위 또는 그에 준하는 경험이 풍부한 ...
1,마케팅 데이터 분석 (브랜드엑셀러레이팅사업부/데이터분석팀),테크랩스,서울 강남구,경력 2-10년,주요업무\n[브랜드 엑셀러레이팅 사업부]\nㆍ고관여 제품이나 서비스의 마케팅 전략과...,자격요건\n? 중상급 수준의 Excel 활용이 가능하신 분(필수)\n? 종합적 사고...,우대사항\n? 사회과학 계열 통계를 학습하신 분\n? 데이터 분석 관련 자격증(사회...
2,Data Scientist (산업기능요원),트릿지,서울 서초구,신입-경력 5년,주요업무\n이러한 업무를 수행합니다:\n\n? Tridge의 독점 데이터와 시장 경...,자격요건\n이러한 역량과 경험이 있는 분들을 찾습니다:\n\n? (필수) 정보처리 ...,우대사항\n이러한 강점이 있다면 더욱 좋습니다:\n\n? 데이터 분석 및 모델 개발...

In [2]:
df_cleaned = df.dropna()

df_cleaned = df_cleaned.applymap(lambda x: x.strip() if isinstance(x, str) else x)

df_cleaned.columns = ['Job_Title', 'Company_Name', 'Location', 'Experience', 'Main_Tasks', 'Qualifications', 'Preferences']

df_cleaned.head(3)

C:\Users\User\AppData\Local\Temp\ipykernel_23292\1290713222.py:3: FutureWarning: DataFrame.applymap has been deprecated. Use DataFrame.map instead.
  df_cleaned = df_cleaned.applymap(lambda x: x.strip() if isinstance(x, str) else x)

,Job_Title,Company_Name,Location,Experience,Main_Tasks,Qualifications,Preferences
0,데이터 분석가 (3년차 이상),파이프트리스마트팜(PAIPTREESmartFarmInc.),서울 강남구,경력 3년 이상,주요업무\n? 농장의 환경 및 생체 데이터 전처리 및 feature를 추출합니다.\...,자격요건\n? 통계분석 및 모델링 개발의 리딩 경험이 풍부하신 분.\n? 3년 이상...,우대사항\n? ML/DL 관련 분야 석/박사 학위 또는 그에 준하는 경험이 풍부한 ...
1,마케팅 데이터 분석 (브랜드엑셀러레이팅사업부/데이터분석팀),테크랩스,서울 강남구,경력 2-10년,주요업무\n[브랜드 엑셀러레이팅 사업부]\nㆍ고관여 제품이나 서비스의 마케팅 전략과...,자격요건\n? 중상급 수준의 Excel 활용이 가능하신 분(필수)\n? 종합적 사고...,우대사항\n? 사회과학 계열 통계를 학습하신 분\n? 데이터 분석 관련 자격증(사회...
2,Data Scientist (산업기능요원),트릿지,서울 서초구,신입-경력 5년,주요업무\n이러한 업무를 수행합니다:\n\n? Tridge의 독점 데이터와 시장 경...,자격요건\n이러한 역량과 경험이 있는 분들을 찾습니다:\n\n? (필수) 정보처리 ...,우대사항\n이러한 강점이 있다면 더욱 좋습니다:\n\n? 데이터 분석 및 모델 개발...

In [3]:
data_analyst = df_cleaned[df_cleaned['Job_Title'].str.contains('analyst|Data\s*Analyst|데이터\s*분석가*', case=False, na=False)]
data_scientist = df_cleaned[df_cleaned['Job_Title'].str.contains('scientist|Data\s*Scientist|데이터\s*과학자', case=False, na=False)]

In [4]:
print(len(data_analyst))
data_analyst.head(3)

82

,Job_Title,Company_Name,Location,Experience,Main_Tasks,Qualifications,Preferences
0,데이터 분석가 (3년차 이상),파이프트리스마트팜(PAIPTREESmartFarmInc.),서울 강남구,경력 3년 이상,주요업무\n? 농장의 환경 및 생체 데이터 전처리 및 feature를 추출합니다.\...,자격요건\n? 통계분석 및 모델링 개발의 리딩 경험이 풍부하신 분.\n? 3년 이상...,우대사항\n? ML/DL 관련 분야 석/박사 학위 또는 그에 준하는 경험이 풍부한 ...
1,마케팅 데이터 분석 (브랜드엑셀러레이팅사업부/데이터분석팀),테크랩스,서울 강남구,경력 2-10년,주요업무\n[브랜드 엑셀러레이팅 사업부]\nㆍ고관여 제품이나 서비스의 마케팅 전략과...,자격요건\n? 중상급 수준의 Excel 활용이 가능하신 분(필수)\n? 종합적 사고...,우대사항\n? 사회과학 계열 통계를 학습하신 분\n? 데이터 분석 관련 자격증(사회...
5,제품 Data Analyst (Senior),바비톡,서울 서초구,경력 7년 이상,주요업무\n? Data-driven 의사결정을 내릴 수 있도록 정량적 수치와 분석 ...,자격요건\n? DA 경력 7년 이상 혹은 이에 준하는 실력\n? 주제별 데이터 분석...,우대사항\n? Lean Startup 및 Agile 조직 경험이 있으신 분\n? 데...

In [5]:
import re

def convert_experience(exp):
    # 경력 X년 이상
    match = re.match(r'경력\s*(\d+)\s*년\s*이상', exp)
    if match:
        return f"{match.group(1)}~"
    
    # 경력 X년 이하
    match = re.match(r'경력\s*(\d+)\s*년\s*이하', exp)
    if match:
        return f"0~{match.group(1)}"
    
    # 경력 X년 - Y년
    match = re.match(r'경력\s*(\d+)\s*-\s*(\d+)\s*년', exp)
    if match:
        return f"{match.group(1)}~{match.group(2)}"
    
    # 신입 - 경력 X년
    match = re.match(r'신입\s*-\s*경력\s*(\d+)\s*년', exp)
    if match:
        return f"0~{match.group(1)}"
    
    # 경력 X년
    match = re.match(r'경력\s*(\d+)\s*년', exp)
    if match:
        return f"{match.group(1)}~{match.group(1)}"
    
    # 신입
    match = re.match(r'신입', exp)
    if match:
        return "0~0"
    
    return exp

data_analyst['Experience'] = data_analyst['Experience'].apply(convert_experience)
data_analyst.head(3)

C:\Users\User\AppData\Local\Temp\ipykernel_23292\2066801743.py:36: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data_analyst['Experience'] = data_analyst['Experience'].apply(convert_experience)

,Job_Title,Company_Name,Location,Experience,Main_Tasks,Qualifications,Preferences
0,데이터 분석가 (3년차 이상),파이프트리스마트팜(PAIPTREESmartFarmInc.),서울 강남구,3~,주요업무\n? 농장의 환경 및 생체 데이터 전처리 및 feature를 추출합니다.\...,자격요건\n? 통계분석 및 모델링 개발의 리딩 경험이 풍부하신 분.\n? 3년 이상...,우대사항\n? ML/DL 관련 분야 석/박사 학위 또는 그에 준하는 경험이 풍부한 ...
1,마케팅 데이터 분석 (브랜드엑셀러레이팅사업부/데이터분석팀),테크랩스,서울 강남구,2~10,주요업무\n[브랜드 엑셀러레이팅 사업부]\nㆍ고관여 제품이나 서비스의 마케팅 전략과...,자격요건\n? 중상급 수준의 Excel 활용이 가능하신 분(필수)\n? 종합적 사고...,우대사항\n? 사회과학 계열 통계를 학습하신 분\n? 데이터 분석 관련 자격증(사회...
5,제품 Data Analyst (Senior),바비톡,서울 서초구,7~,주요업무\n? Data-driven 의사결정을 내릴 수 있도록 정량적 수치와 분석 ...,자격요건\n? DA 경력 7년 이상 혹은 이에 준하는 실력\n? 주제별 데이터 분석...,우대사항\n? Lean Startup 및 Agile 조직 경험이 있으신 분\n? 데...

In [6]:
data_analyst[['Company_Name','Location','Experience']].to_csv('data_analyst_Ex.csv', index=False, encoding='cp949')

In [7]:
import re
from sklearn.feature_extraction.text import TfidfVectorizer
import pandas as pd

# 주요 업무에 있을 만한 한국어 불용어 리스트
korean_stop_words = [
    '및', '을', '를', '에', '의', '가', '이', '은', '는', '들', '으로', '하다', '있다', '수', '등', '및', '에서', '이다',
    '그리고', '또한', '하지만', '그러나', '때문에', '따라서', '그러므로', '즉', '예를', '들면', '예를', '들어', '같은', '경우',
    '때문', '위해', '통해', '대한', '대해', '관련', '관련된', '관련하여', '관한', '관해서', '위한', '위해서', '와', '하고',
    '합니다', 'ㆍ', '따른', '하여', '합니다', '있어요', '해요', '해', '한', '필요', '주요업무', '있도록', '있습니다', '있으신', '우대사항', '과',
    '하신', '원활히', '하거나', '으신', '있으면', '더욱', '이나', '분이면', '하게', '자격요건', '할', '년', '찾아요', '함께',
    '갖추고', '로', '주실', '생기면', '보실', '하셨거나', '있게'
    
]


def remove_stop_words(text, stop_words):
    pattern = re.compile(r'\b(' + '|'.join(stop_words) + r')\b|\b(' + '|'.join(stop_words) + r')\w*\b|\b\w*(' + '|'.join(stop_words) + r')\b')
    return pattern.sub('', text)

want = ['Main_Tasks', 'Qualifications','Preferences']

for i in want:
    data_analyst[i] = data_analyst[i].apply(lambda x: remove_stop_words(x, korean_stop_words))
    for j in range(2):
        vectorizer = TfidfVectorizer(ngram_range=(j+1, j+1))
        X = vectorizer.fit_transform(data_analyst[i])

        tfidf_scores = X.sum(axis=0).A1
        tfidf_scores_df = pd.DataFrame({'term': vectorizer.get_feature_names_out(), 'score': tfidf_scores})
        tfidf_scores_df = tfidf_scores_df.sort_values(by='score', ascending=False)

        top_keywords = tfidf_scores_df.head(50 if j == 0 else 30)
        print(top_keywords)
        top_keywords.to_csv(f'{i}_TopKeywords_{j+1}.csv', index=False, encoding='cp949')

         term      score
265       데이터  11.133898
387        분석   8.221494
447        설계   4.563188
400      비즈니스   4.277581
442       서비스   4.063249
695        지표   3.901071
174        고객   3.526663
186        관리   3.343978
140        개발   3.337835
300       마케팅   3.184277
577        운영   2.886401
602      인사이트   2.849765
795      프로덕트   2.829086
218        기반   2.691183
273        도출   2.684816
346        문제   2.645693
482       시각화   2.560587
163        게임   2.524999
260      대시보드   2.501026
684        주요   2.384576
49       data   2.382477
666        제공   2.317094
645        전략   2.133656
668        제안   2.066077
761       테스트   2.042942
224        기획   2.033046
504        실험   1.835459
671        제품   1.833649
201        구축   1.783278
816        핵심   1.775280
483       시계열   1.761495
77        kpi   1.696203
160        검증   1.556858
799      프로젝트   1.554260
330       모델링   1.532677
337        목표   1.495771
535        업무   1.493259
412        사업   1.491861
327      모니터링   1.462758
189        광고   1.459487
693        지원   1.441116
729        추출   1.429731
767    통계프로그램   1.404539
669        제작   1.402159
418       사용자   1.398861
650        전사   1.387685
296       리포트   1.367828
33   business   1.354320
502        실행   1.331302
320      머신러닝   1.318645
            term     score
525       데이터 분석  3.377606
506       데이터 기반  1.736285
535      데이터 시각화  1.476296
1338     인사이트 도출  1.466549
1131  시계열 통계프로그램  1.414214
1678   통계프로그램 개발  1.414214
1177       실험 설계  1.131739
500       데이터 관리  1.092096
305       고객 데이터  1.058012
108      etl cep  1.000000
839       분석 데이터  0.950219
335       관리 데이터  0.923172
918     비즈니스 데이터  0.918405
923      비즈니스 문제  0.906806
1436      정량적 분석  0.881046
215        개발 관리  0.846797
1770       핵심 지표  0.797718
1552       지표 설계  0.790940
858        분석 설계  0.750831
563       데이터 추출  0.733938
1343     인사이트 제공  0.700620
1399       전략 분석  0.696521
509      데이터 데이터  0.685335
1512     주요 비즈니스  0.670433
870      분석 인사이트  0.662004
1059       설계 분석  0.661735
478      대시보드 구축  0.654148
271       게임 데이터  0.651965
1117    시각화 대시보드  0.648880
1740    프로젝트 데이터  0.644351
        term      score
219      데이터  11.686845
287       분석  11.074743
146       경험   4.417991
196       능력   4.198465
142       경력   4.039587
90    python   4.012336
108      sql   3.882308
510   커뮤니케이션   3.093314
311       사용   2.862598
189      논리적   2.847673
506       추출   2.839175
326      서비스   2.665194
491       찾고   2.646304
386       업무   2.640667
526       통계   2.570380
112  tableau   2.504146
358      시각화   2.421009
297     비즈니스   2.417877
124      갖추신   2.353882
383       언어   2.326172
395       역량   2.121808
264       문제   2.086763
365       실무   2.012080
578       활용   1.975721
529      통계학   1.887049
514      코호트   1.861902
23        bi   1.743558
559       학사   1.705253
259      모델링   1.689213
281       보유   1.680680
484       직접   1.675175
409       유관   1.624940
260      모바일   1.618034
45     excel   1.614981
412     인사이트   1.614640
171       기반   1.599940
503       최소   1.558401
51    funnel   1.534130
293       분야   1.451259
56    google   1.447798
26    cohort   1.439417
479       지식   1.414198
95    redash   1.413097
282      보유자   1.387309
127       개선   1.384831
224       도출   1.362003
505       추론   1.360002
548     프로그램   1.336982
321       상급   1.318620
330       설계   1.315242
                 term     score
484            데이터 분석  4.893811
206        sql python  2.373489
510            데이터 추출  2.010927
1159           코호트 분석  1.606714
494           데이터 시각화  1.512807
157        python 데이터  1.369037
688             분석 실무  1.324533
1140            추출 분석  1.284404
813           서비스 데이터  1.250362
589           모바일 서비스  1.221259
692             분석 업무  1.212051
710            분석 코호트  1.158707
669             분석 방법  1.140746
655             분석 경험  1.109660
153        python sql  1.099707
1111           찾고 데이터  1.087444
409            논리적 추론  1.072971
654             분석 경력  1.036491
52    cohort analysis  1.013706
673             분석 분석  0.983962
938            업무 데이터  0.961048
299            경력 데이터  0.948141
1199            퍼널 분석  0.941069
713            분석 테스트  0.905532
1116          찾습니다 읽고  0.894427
411          논리적 통계학적  0.894427
1005           읽고 논리적  0.894427
1191         통계학적 데이터  0.894427
515            데이터 탐정  0.894427
479           데이터 데이터  0.880631
        term     score
248      데이터  9.133872
353       분석  5.722958
175       경험  5.377015
366     비즈니스  3.570086
737       활용  3.286028
439      시각화  2.753366
607      좋아요  2.690503
403      서비스  2.682832
141  tableau  2.629813
197       구축  2.541119
390     산업공학  2.209689
473       업무  2.202227
27        bi  2.169059
118   python  1.926053
159       개발  1.878197
484       영어  1.860860
682       통계  1.823347
684      통계학  1.795836
310      모델링  1.776896
671    컴퓨터공학  1.766399
670      컴퓨터  1.696114
43      data  1.676290
569       전공  1.665871
691    파이프라인  1.651268
710     프로젝트  1.626951
176      경험자  1.620007
320       물류  1.480906
411       설계  1.469752
125   redash  1.434278
664      커머스  1.399546
169       게임  1.367940
211       기반  1.346840
188       관리  1.335690
296      마케팅  1.332648
681      테스트  1.279363
678     클라우드  1.266107
732       환경  1.255167
500       운영  1.233784
524      인터뷰  1.232640
318       문제  1.165567
380       사용  1.147251
276       레벨  1.144374
73        it  1.134610
9      agile  1.125565
81    looker  1.117040
22       aws  1.108715
624       지원  1.104540
717       학위  1.090377
112    power  1.089239
683      통계적  1.082542
                term     score
456           데이터 분석  3.491136
464          데이터 시각화  2.294112
186       python 데이터  1.483102
861      시각화 tableau  1.453711
1242      컴퓨터공학 산업공학  1.412355
1281        파이프라인 구축  1.268355
53             bi 활용  1.219613
484        데이터 파이프라인  1.123228
446          데이터 데이터  1.065633
1252         클라우드 환경  1.046567
724          비즈니스 레벨  0.996024
1364          활용 데이터  0.948080
178         power bi  0.943898
1076         전공 클라우드  0.927602
1349           환경 경험  0.927602
772          산업공학 전공  0.927602
304           경험 데이터  0.921705
680          분석 리더로서  0.909443
82    data warehouse  0.903424
241     warehouse 구축  0.903424
1135         좋아요 데이터  0.902542
229   tableau redash  0.901427
307          경험 비즈니스  0.890109
731         비즈니스 컨설팅  0.890109
1236          컨설팅 경험  0.890109
51            bi 데이터  0.855078
227    tableau power  0.849370
673            분석 경험  0.831733
433          대용량 데이터  0.822917
729          비즈니스 영어  0.802483

C:\Users\User\AppData\Local\Temp\ipykernel_23292\2766348458.py:24: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data_analyst[i] = data_analyst[i].apply(lambda x: remove_stop_words(x, korean_stop_words))
C:\Users\User\AppData\Local\Temp\ipykernel_23292\2766348458.py:24: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data_analyst[i] = data_analyst[i].apply(lambda x: remove_stop_words(x, korean_stop_words))
C:\Users\User\AppData\Local\Temp\ipykernel_23292\2766348458.py:24: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data_analyst[i] = data_analyst[i].apply(lambda x: remove_stop_words(x, korean_stop_words))